function renderTools(){const p=state.plan;document.getElementById('panel-tools').innerHTML=`<div class="card"><div class="kicker">每本书只选最合适的1–2个</div><h3>这本书的思维工具</h3><p class="muted">思维模型不是装饰。填完以后点“让AI帮我看看”，AI只会给启发，不会替你填满。</p><div class="toolGrid">${p.thinkingTools.map((t,i)=>toolHTML(t,i)).join('')}</div></div>`;bindToolInputs()}
function toolHTML(t,i){const id=resolveId(t);return `<div class="toolCard" data-tool-index="${i}"><div class="kicker">工具 ${i+1}</div><h4>${esc(t.name||modelNames[id]||'思维工具')}</h4><div class="why">${esc(t.whyFit||'')}</div><div class="toolArea">${templateHTML(id,t,i)}</div><button class="softBtn feedbackBtn" data-tool="${i}">✨ 让AI帮我看看</button><div class="feedback" id="feedback-${i}" style="display:${state.toolAnswers?.[i]?.feedback?'block':'none'}">${esc(state.toolAnswers?.[i]?.feedback||'')}</div></div>`}
function getTA(i){state.toolAnswers=state.toolAnswers||{};state.toolAnswers[i]=state.toolAnswers[i]||{values:{}};return state.toolAnswers[i]}
function ta(i,key,ph='写下你的发现…'){const v=getTA(i).values[key]||'';return `<textarea data-i="${i}" data-k="${key}" placeholder="${esc(ph)}">${esc(v)}</textarea>`}
function templateHTML(id,t,i){if(id==='timeline')return `<div id="dyn-${i}">${dynamicListHTML(i,'timeline','事件','发生了什么？为什么重要？')}</div><button type="button" class="softBtn addItem" data-i="${i}" data-kind="timeline">＋添加事件</button>`;
if(id==='storyMountain')return `<div class="cols2">${['开端','发展','冲突','高潮','结局'].map(x=>`<div class="miniBox"><strong>${x}</strong>${ta(i,x)}</div>`).join('')}</div>`;
if(id==='doubleBubble')return `<div class="cols3"><div class="miniBox"><strong>A 独有</strong>${ta(i,'A独有','人物A独有的特点/处境')}</div><div class="miniBox"><strong>共同点</strong>${ta(i,'共同点','他们共同重视什么？')}</div><div class="miniBox"><strong>B 独有</strong>${ta(i,'B独有','人物B独有的特点/能力')}</div></div>`;
if(id==='swot')return `<div class="cols4"><div class="miniBox"><strong>S 强项</strong>${ta(i,'S')}</div><div class="miniBox"><strong>W 弱点</strong>${ta(i,'W')}</div><div class="miniBox"><strong>O 机会</strong>${ta(i,'O')}</div><div class="miniBox"><strong>T 风险</strong>${ta(i,'T')}</div></div>`;
if(id==='logicTree')return `<div class="field"><label>最上面的“大问题”</label>${ta(i,'root','例如：为什么主角会做这个选择？')}</div><div id="dyn-${i}">${dynamicListHTML(i,'logic','分支','把大问题拆成一个小问题')}</div><button type="button" class="softBtn addItem" data-i="${i}" data-kind="logic">＋添加分支</button>`;
if(id==='characterMap')return `<div class="field"><label>中心人物</label>${ta(i,'center','谁放在中心？')}</div><div id="dyn-${i}">${dynamicListHTML(i,'relation','关系','人物A → 关系动词 → 中心人物')}</div><button type="button" class="softBtn addItem" data-i="${i}" data-kind="relation">＋添加关系</button>`;
if(id==='decisionMatrix')return `<div class="cols2"><div class="miniBox"><strong>方案A + 评分理由</strong>${ta(i,'A')}</div><div class="miniBox"><strong>方案B + 评分理由</strong>${ta(i,'B')}</div><div class="miniBox"><strong>比较标准</strong>${ta(i,'criteria','安全/公平/代价/效果…')}</div><div class="miniBox"><strong>我的决定</strong>${ta(i,'decision')}</div></div>`;
if(id==='empathyMap')return `<div class="cols4"><div class="miniBox"><strong>看到</strong>${ta(i,'看到')}</div><div class="miniBox"><strong>听到</strong>${ta(i,'听到')}</div><div class="miniBox"><strong>想到/感到</strong>${ta(i,'想到感到')}</div><div class="miniBox"><strong>说和做</strong>${ta(i,'说和做')}</div></div>`;
const prompts=(t.prompts||['我已经确定的事实','我发现的关系/变化','这说明了什么？']);return prompts.map((x,k)=>`<div class="field"><label>${esc(x)}</label>${ta(i,'p'+k)}</div>`).join('')}
function dynamicListHTML(i,kind,label,ph){const a=getTA(i).values[kind]||[''];return a.map((v,k)=>`<div class="field"><label>${label}${k+1}</label><input data-i="${i}" data-arr="${kind}" data-pos="${k}" value="${esc(v)}" placeholder="${esc(ph)}" /></div>`).join('')}
function bindToolInputs(){document.querySelectorAll('[data-i][data-k]').forEach(el=>el.addEventListener('input',e=>{getTA(+e.target.dataset.i).values[e.target.dataset.k]=e.target.value;save()}));document.querySelectorAll('[data-i][data-arr]').forEach(el=>el.addEventListener('input',e=>{const i=+e.target.dataset.i,k=e.target.dataset.arr,p=+e.target.dataset.pos;getTA(i).values[k]=getTA(i).values[k]||[];getTA(i).values[k][p]=e.target.value;save()}));document.querySelectorAll('.addItem').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,k=b.dataset.kind;getTA(i).values[k]=getTA(i).values[k]||[''];getTA(i).values[k].push('');renderTools()});document.querySelectorAll('.feedbackBtn').forEach(b=>b.onclick=()=>feedbackForTool(+b.dataset.tool))}
async function feedbackForTool(i){const t=state.plan.thinkingTools[i],ans=getTA(i).values;setLoading(true,'AI正在看你的思维图，不会替你填答案…');try{const sys=`你是小学${state.grade}年级的阅读导师。${gradeLanguage(state.grade)}。你只做启发式反馈：第一句指出孩子已经做对/看见的一个具体点；第二句指出一个还可以继续想的地方；最后只问1个问题。不要给标准答案，不要替孩子补完整。不使用“好词好句”。`;const resp=await aiChat([{role:'system',content:sys},{role:'user',content:`书名：《${state.plan.title}》\n思维工具：${t.name}\n孩子填写：${JSON.stringify(ans)}`}]);getTA(i).feedback=responseText(resp)||'我看到了你的思考。再试着找一个“为什么”或“如果换个选择会怎样”？';renderTools();save()}catch(e){getTA(i).feedback='你的图已经有了自己的判断。下一步只追问一个问题：其中哪一条关系最能改变全书的走向？为什么？';renderTools()}finally{setLoading(false)}}
function renderDiscuss(){const q=state.plan.discussionQuestions||[];document.getElementById('panel-discuss').innerHTML=`<div class="card"><div class="kicker">不是做题，是讨论</div><h3>把书读深一点</h3><p class="muted">你不需要一次回答完。选一个最想说的，在右侧告诉AI阅读导师。</p>${q.map((x,i)=>`<div class="question"><b>Q${i+1}</b>　${esc(x)}</div>`).join('')}</div>`}
function renderProject(){const f=state.plan.finalProject||{};document.getElementById('panel-project').innerHTML=`<div class="card drive"><div class="kicker">最终作品</div><h3>${esc(f.title||'我的阅读项目')}</h3><p class="muted">${esc(f.brief||'')}</p></div><div class="card"><h3>怎么完成</h3><div class="projectSteps">${(f.steps||[]).map((s,i)=>`<div class="step"><i>${i+1}</i><div>${esc(s)}</div></div>`).join('')}</div></div><div class="card"><h3>成功标准</h3><div class="rubric">${(f.rubric||[]).map(x=>`<div>✓ ${esc(x)}</div>`).join('')}</div><p class="muted" style="margin-top:15px">当前难度：${state.grade}年级。${state.grade<=2?'可以用画+关键词+口述完成，不要求长篇写作。':state.grade<=4?'要能说明“为什么”，作品中至少出现一处因果或比较。':'要有证据、反例或价值冲突中的至少一种，并能为自己的结论辩护。'}</p></div>`}
function renderChat(){const box=document.getElementById('messages');if(!state.chat?.length)state.chat=[{role:'ai',content:`你好！我们正在读《${state.plan.title}》。我不会替你总结成“标准答案”。先告诉我：你现在最想弄懂的是一个人物、一次选择，还是一个情节转折？`}];box.innerHTML=state.chat.map(m=>`<div class="msg ${m.role==='user'?'user':'ai'}">${esc(m.content)}</div>`).join('');box.scrollTop=box.scrollHeight}
async function sendChat(text){if(!text.trim())return;state.chat.push({role:'user',content:text.trim()});renderChat();save();const input=document.getElementById('chatInput');input.value='';const temp={role:'ai',content:'正在想一个能让你继续发现的问题…'};state.chat.push(temp);renderChat();try{const sys=`你是AI阅读导师，面向小学${state.grade}年级。当前书名《${state.plan.title}》，体裁${state.plan.genre}，驱动问题：${state.plan.drivingQuestion}。${gradeLanguage(state.grade)}。你绝不提供“标准答案”、不要求摘好词好句、不把阅读变成考试。优先用追问帮助孩子发现人物关系、变化、因果、选择与证据。一次最多问1-2个问题。回复尽量100-180字以内。不要长篇复述原书。`;const hist=state.chat.slice(-9,-1).map(m=>({role:m.role==='ai'?'assistant':'user',content:m.content}));const resp=await aiChat([{role:'system',content:sys},...hist,{role:'user',content:text.trim()}]);temp.content=responseText(resp)||'你已经抓到一个点了。接着想：你是从哪件事看出来的？如果把这个选择换掉，后面可能会有什么不同？'}catch(e){temp.content='我先不替你补答案。你可以再往前走一步：这件事“为什么”会发生？如果换一个角色来做决定，结果会不会不一样？'}renderChat();save()}
function initUI(){document.getElementById('chips').innerHTML=quick.map(x=>`<button class="chip" data-book="${x}">${x}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.getElementById('bookInput').value=b.dataset.book});document.getElementById('booklist').innerHTML=Object.entries(rawBooks).map(([g,arr])=>`<div class="gradecol"><b>${g}年级</b><p>${arr.slice(0,6).map(x=>x[0]).join(' · ')}${arr.length>6?' …':''}</p></div>`).join('');document.getElementById('bookForm').onsubmit=async e=>{e.preventDefault();const title=document.getElementById('bookInput').value.trim();if(!title)return;setLoading(true);const p=await analyze(title);setLoading(false);state={plan:p,grade:p.recommendedGrade||3,toolAnswers:{},chat:[]};openWorkspace();if(p._error){const er=document.getElementById('homeError');er.textContent='AI连接刚才没有成功，所以我先打开了可用的通用精读路线。你仍然可以继续使用思维工具。';}};document.getElementById('demoBtn').onclick=()=>{const p=demoCharlotte();state={plan:p,grade:3,toolAnswers:{},chat:[]};openWorkspace()};document.getElementById('restartBtn').onclick=()=>{localStorage.removeItem('ai-reading-agent-v2');location.reload()};document.getElementById('gradeSelect').onchange=e=>{state.grade=+e.target.value;renderProject();renderChat();save()};document.getElementById('tabs').onclick=e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById('panel-'+b.dataset.tab).classList.add('active')};document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();sendChat(document.getElementById('chatInput').value)};document.getElementById('chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();document.getElementById('chatForm').requestSubmit()}};loadSaved()}
initUI();