function fallbackPlan(title,meta){const g=meta?.grade||3, genre=meta?.genre||'整本书阅读', mids=meta?.models||['storyMountain','causeEffect'];return {title,author:'待确认',genre,recommendedGrade:g,difficulty:g<=2?'入门':g<=4?'进阶':'挑战',confidence:'low',bookIntro:'先不急着找标准答案。我们会从人物、事件、变化和选择入手，逐步搭起这本书的整体理解。',drivingQuestion:'这本书里，什么样的选择最能改变一个人（或一件事）的走向？为什么？',wholeBookMap:[{title:'进入故事/主题',goal:'认识主要人物、场景或核心问题'},{title:'变化发生',goal:'发现第一个重要变化，并猜它会带来什么'},{title:'冲突与选择',goal:'找出最难的一次选择或最大的难题'},{title:'转折与结果',goal:'追踪一个选择怎样产生后果'},{title:'回看整本书',goal:'用一个模型解释全书最重要的变化'}],thinkingTools:mids.slice(0,2).map(id=>({id,name:modelNames[id]||id,whyFit:'它能帮你把“发生了什么”变成“我看懂了什么关系”。',prompts:['先把你确定的事实写下来','再找变化、共同点或因果关系','最后问：这说明了什么？'],expectedOutput:'一张能说清关系和变化的思维图'})),discussionQuestions:['哪个人物（或观点）变化最大？为什么？','如果把一个关键选择换掉，后面可能会怎样？','你觉得书里最值得讨论的冲突是什么？','哪一处情节最能支持你的判断？'],finalProject:{title:'“一个选择如何改变全书”阅读展板',brief:'选一个关键选择，用图和短句说明它怎样影响后续发展，再提出你的替代方案。',steps:['选定一个关键选择','用思维工具整理原因和后果','设计一个替代选择','做成一张可展示的阅读作品'],rubric:['能说清前因后果','至少使用1个思维工具','有自己的判断，不只复述情节','作品让别人一眼看懂']}}}
function demoCharlotte(){return {title:'夏洛的网',author:'E. B. 怀特',genre:'儿童小说',recommendedGrade:3,difficulty:'进阶',confidence:'high',bookIntro:'威尔伯是一只小猪，夏洛是一只蜘蛛。他们在谷仓里成为朋友，而这段友谊最终改变了彼此的命运。',drivingQuestion:'真正的朋友会为彼此做什么？一个看起来很普通的个体，怎样通过自己的行动改变另一个人的命运？',wholeBookMap:[{title:'相遇：威尔伯需要什么？',goal:'从威尔伯的处境出发，理解他的孤独与需要'},{title:'关系形成：谁在改变谁？',goal:'观察夏洛、威尔伯和谷仓伙伴之间的关系'},{title:'危机出现：怎样面对不可避免的问题？',goal:'找出威尔伯面临的核心危机与不同角色的反应'},{title:'行动与代价：夏洛做了哪些选择？',goal:'追踪“行动—影响—代价”的因果链'},{title:'结局回看：友谊留下了什么？',goal:'比较人物前后变化，回答驱动性问题'}],thinkingTools:[{id:'doubleBubble',name:'双重气泡图',whyFit:'威尔伯和夏洛差异很大，却形成了深厚友谊。比较“不同”与“共同”最能看见这段关系为什么成立。',prompts:['威尔伯独有的性格/处境是什么？','两者共同重视什么？','夏洛独有的能力/选择是什么？'],expectedOutput:'威尔伯 vs 夏洛双重气泡图'},{id:'characterMap',name:'人物关系图',whyFit:'谷仓里每个角色与威尔伯的关系不同。把关系画出来，可以发现“谁在支持、谁在影响、关系如何变化”。',prompts:['先放中心人物威尔伯','添加夏洛、芬、坦普尔顿等关键人物','给每条关系写一个动词：帮助/依赖/影响/冲突…'],expectedOutput:'一张会“说话”的人物关系图'}],discussionQuestions:['威尔伯一开始最需要的是“活下来”还是“被陪伴”？为什么？','夏洛帮助威尔伯，是因为责任、友谊，还是别的原因？你从哪些情节判断？','坦普尔顿看起来并不无私，但他为什么仍然是关系网里重要的一环？','如果夏洛没有想到用“文字”改变人类对威尔伯的看法，还有什么办法？','到故事后面，威尔伯有没有也在“帮助夏洛”？这段关系是否从单向帮助变成了双向？'],finalProject:{title:'友谊行动博物馆',brief:'你是小小策展人。选3—5个“行动展品”，说明一个普通角色怎样通过行动改变另一个生命的命运。',steps:['确定展览主问题：真正的朋友会为彼此做什么？','选择3—5个关键行动作为“展品”','用双重气泡图或人物关系图解释行动背后的关系','给每件展品写“行动—影响—代价”说明牌','设计结尾互动：让参观者投票“最重要的行动是什么？”'],rubric:['不是复述故事，而是在解释“为什么”','至少正确使用1个思维工具','每个判断都有情节依据','能让别人看完后形成自己的观点']}}}
async function analyze(title){const meta=getMeta(title);const system=`你是面向中国小学1-6年级的AI整本书阅读导师，懂PBL项目式学习和可视化思维工具。你绝不把阅读变成好词好句摘抄、中心思想标准答案或刷题。你的目标是让孩子发现人物关系、结构、变化、因果、选择和证据。不要大段复述或引用受版权保护的原文。若对冷门书细节不确定，confidence必须降低，并使用不捏造细节的通用整本书路径。输出必须是纯JSON，不要markdown。JSON字段：title,author,genre,recommendedGrade(1-6整数),difficulty,confidence(high/medium/low),bookIntro(80字内),drivingQuestion,wholeBookMap(3-6项，每项title,goal),thinkingTools(恰好2项，每项id,name,whyFit,prompts数组,expectedOutput；id优先从 timeline,storyMountain,doubleBubble,characterMap,causeEffect,fishbone,logicTree,5w1h,swot,pest,decisionTree,decisionMatrix,empathyMap,iceberg,characterArc,themeEvidence,problemSolution,comparison,sixHats,stakeholder,cer,causalLoop,valueConflict,prediction,storyWorld 选择),discussionQuestions(4-6项),finalProject{title,brief,steps(3-5),rubric(3-4)}。驱动性问题必须开放、可探究、和人的选择或现实有关。每本书只选最合适的1-2个思维模型。`;
const hint=meta?`书库信息：建议${meta.grade}年级，体裁${meta.genre}，优先模型${meta.models.join(',')}。请校正但不要机械照抄。`: '这本书不在本地初始书库。请根据你可靠掌握的信息识别；不确定就降低confidence，绝不要编造具体章节。';
const user=`请为《${title}》生成整本书精读项目。${hint}`;
let opts={};if(!meta)opts={model:'openai/gpt-5.6-luna',normalize:true,tools:[{type:'web_search'}]};
try{const resp=await puter.ai.chat([{role:'system',content:system},{role:'user',content:user}],opts.model?opts:{model:MODEL,normalize:true});const plan=parseJSON(responseText(resp));if(!plan)throw new Error('AI返回格式无法解析');return sanitizePlan(plan,title,meta)}catch(err){console.warn(err);const p=fallbackPlan(title,meta);p._error=String(err?.message||err);return p}}
function sanitizePlan(p,title,meta){p.title=p.title||title;p.recommendedGrade=Math.max(1,Math.min(6,Number(p.recommendedGrade)||meta?.grade||3));p.genre=p.genre||meta?.genre||'整本书';p.confidence=['high','medium','low'].includes(p.confidence)?p.confidence:'medium';p.wholeBookMap=Array.isArray(p.wholeBookMap)?p.wholeBookMap.slice(0,6):[];p.thinkingTools=Array.isArray(p.thinkingTools)?p.thinkingTools.slice(0,2):[];if(p.thinkingTools.length<2){const fb=fallbackPlan(title,meta).thinkingTools;p.thinkingTools=[...p.thinkingTools,...fb].slice(0,2)}p.discussionQuestions=Array.isArray(p.discussionQuestions)?p.discussionQuestions.slice(0,6):[];p.finalProject=p.finalProject||fallbackPlan(title,meta).finalProject;return p}
function save(){localStorage.setItem('ai-reading-agent-v2',JSON.stringify(state))}
function loadSaved(){try{const s=JSON.parse(localStorage.getItem('ai-reading-agent-v2'));if(s?.plan){state=s;openWorkspace()}}catch(e){}}
function openWorkspace(){document.getElementById('home').style.display='none';document.getElementById('libraryInfo').style.display='none';document.getElementById('workspace').style.display='block';renderAll();window.scrollTo({top:0})}
function renderAll(){const p=state.plan;if(!p)return;document.getElementById('bookTitle').textContent='《'+p.title.replace(/[《》]/g,'')+'》';document.getElementById('authorPill').textContent='作者：'+(p.author||'待确认');document.getElementById('genrePill').textContent='体裁：'+(p.genre||'—');document.getElementById('difficultyPill').textContent='难度：'+(p.difficulty||'—');document.getElementById('confidencePill').textContent='识别：'+({high:'高',medium:'中',low:'谨慎模式'}[p.confidence]||p.confidence);document.getElementById('gradeSelect').value=String(state.grade||p.recommendedGrade||3);renderIntro();renderMap();renderTools();renderDiscuss();renderProject();renderChat();save()}
function renderIntro(){const p=state.plan;document.getElementById('panel-intro').innerHTML=`<div class="card"><div class="kicker">先看全书，不急着做题</div><h3>这本书大概在讲什么？</h3><p class="muted">${esc(p.bookIntro)}</p>${p.confidence==='low'?'<div class="feedback">这本书的信息把握有限，我会避免假装知道具体章节，先用“通用整本书路线”陪你读。你不需要粘贴原文。</div>':''}</div><div class="card drive"><div class="kicker">PBL 驱动性问题</div><div class="q">${esc(p.drivingQuestion)}</div><p class="muted">这不是一道“答完就结束”的题。你会带着它读完整本书，并在最后用作品回答它。</p></div><div class="card"><h3>你的阅读方式</h3><div class="cols3"><div class="miniBox"><strong>① 看关系</strong><span class="muted">人物、事件、观点之间有什么联系？</span></div><div class="miniBox"><strong>② 看变化</strong><span class="muted">什么在前后发生了变化？为什么？</span></div><div class="miniBox"><strong>③ 做作品</strong><span class="muted">把你的发现变成别人能看懂的成果。</span></div></div></div>`}
function renderMap(){const p=state.plan;document.getElementById('panel-map').innerHTML=`<div class="card"><div class="kicker">Whole-book map</div><h3>整本书阅读地图</h3><p class="muted">不用每一章都做一张表。我们只抓住真正改变全书走向的阶段。</p><div class="map">${p.wholeBookMap.map((s,i)=>`<div class="stage"><div class="num">${i+1}</div><div><b>${esc(s.title||'阶段'+(i+1))}</b><p>${esc(s.goal||'')}</p></div></div>`).join('')}</div></div>`}
function resolveId(t){if(t.id&&modelNames[t.id])return t.id;const n=String(t.name||'');return Object.keys(modelNames).find(k=>n.includes(modelNames[k])||modelNames[k].includes(n))||'generic'}