const MODEL='gpt-5.6-luna';
const quick=['夏洛的网','西游记','鲁滨逊漂流记','小王子','昆虫记','安徒生童话'];
const rawBooks={
1:[['猜猜我有多爱你','图画书','doubleBubble,empathyMap'],['爷爷一定有办法','图画书','timeline,problemSolution'],['逃家小兔','图画书','prediction,empathyMap'],['我爸爸','图画书','empathyMap,comparison'],['我妈妈','图画书','empathyMap,comparison'],['蚯蚓的日记','图画书/科普','timeline,5w1h'],['石头汤','民间故事','causeEffect,storyMountain'],['爱心树','图画书','timeline,valueConflict']],
2:[['小鲤鱼跳龙门','童话','storyMountain,characterArc'],['孤独的小螃蟹','童话','characterMap,empathyMap'],['小狗的小房子','童话','storyMountain,doubleBubble'],['一只想飞的猫','童话','characterArc,causeEffect'],['歪脑袋木头桩','童话','characterArc,empathyMap'],['神笔马良','民间故事','decisionTree,storyMountain'],['七色花','童话','decisionMatrix,valueConflict'],['愿望的实现','童话','doubleBubble,causeEffect'],['一起长大的玩具','童话','timeline,comparison'],['了不起的狐狸爸爸','儿童小说','storyMountain,problemSolution']],
3:[['安徒生童话','童话集','storyMountain,valueConflict'],['格林童话','童话集','comparison,storyMountain'],['稻草人','童话集','empathyMap,stakeholder'],['中国古代寓言','寓言','causeEffect,logicTree'],['伊索寓言','寓言','causeEffect,comparison'],['克雷洛夫寓言','寓言','causeEffect,comparison'],['夏洛的网','儿童小说','doubleBubble,characterMap'],['时代广场的蟋蟀','儿童小说','characterMap,valueConflict'],['长袜子皮皮','儿童小说','doubleBubble,empathyMap'],['窗边的小豆豆','成长纪实','characterArc,timeline']],
4:[['中国神话传说','神话','storyWorld,comparison'],['世界经典神话与传说故事','神话','comparison,storyWorld'],['十万个为什么','科普','logicTree,problemSolution'],['灰尘的旅行','科普','causeEffect,5w1h'],['看看我们的地球','科普','logicTree,causeEffect'],['人类起源的演化过程','科普','timeline,causeEffect'],['昆虫记','科普','5w1h,comparison'],['森林报','科普','timeline,causeEffect'],['海底两万里','科幻小说','storyWorld,characterMap'],['秘密花园','儿童小说','characterArc,causeEffect']],
5:[['中国民间故事','民间故事','comparison,storyMountain'],['欧洲民间故事','民间故事','comparison,storyMountain'],['非洲民间故事','民间故事','comparison,storyWorld'],['西游记','古典小说','characterMap,timeline'],['三国演义','古典小说（适读版）','stakeholder,decisionTree'],['水浒传','古典小说（适读版）','characterMap,valueConflict'],['红楼梦','古典小说（适读版）','characterMap,stakeholder'],['小王子','哲理童话','valueConflict,empathyMap'],['草房子','儿童小说','characterArc,empathyMap'],['城南旧事','儿童小说','timeline,characterArc'],['哈利·波特与魔法石','幻想小说','storyWorld,characterMap']],
6:[['童年','自传体小说','iceberg,characterArc'],['小英雄雨来','儿童小说','decisionTree,timeline'],['爱的教育','日记体小说','themeEvidence,empathyMap'],['鲁滨逊漂流记','冒险小说','swot,problemSolution'],['骑鹅旅行记','幻想小说','characterArc,storyWorld'],['汤姆·索亚历险记','儿童小说','decisionTree,characterArc'],['爱丽丝漫游奇境','幻想小说','storyWorld,logicTree'],['假如给我三天光明','自传','timeline,cer'],['毛毛','幻想小说','causalLoop,valueConflict'],['永远讲不完的故事','幻想小说','storyWorld,themeEvidence'],['数星星','历史小说','pest,valueConflict']]
};
const bookDB={}; Object.entries(rawBooks).forEach(([g,arr])=>arr.forEach(([title,genre,models])=>bookDB[norm(title)]={title,grade:+g,genre,models:models.split(',')}));
const modelNames={timeline:'时间线',storyMountain:'故事山',doubleBubble:'双重气泡图',characterMap:'人物关系图',causeEffect:'因果链',fishbone:'鱼骨图',logicTree:'逻辑树','5w1h':'5W1H',swot:'SWOT',pest:'PEST',decisionTree:'决策树',decisionMatrix:'决策矩阵',empathyMap:'同理心地图',iceberg:'冰山模型',characterArc:'人物成长弧',themeEvidence:'主题—证据矩阵',problemSolution:'问题—解决方案树',comparison:'对比矩阵',sixHats:'六顶思考帽',stakeholder:'利益相关者地图',cer:'观点—证据—推理CER',causalLoop:'系统循环图',valueConflict:'价值冲突图',prediction:'预测—证据—修正',storyWorld:'故事世界地图'};
const templateModels=new Set(['timeline','storyMountain','doubleBubble','characterMap','swot','logicTree','decisionMatrix','empathyMap']);
let state={plan:null,grade:3,toolAnswers:{},chat:[]};
function norm(s){return String(s||'').replace(/[《》\s·・.（）()]/g,'').toLowerCase()}
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
function setLoading(on,text){document.getElementById('loading').classList.toggle('on',on);if(text)document.getElementById('loadingText').textContent=text}
function getMeta(title){let n=norm(title);return bookDB[n]||Object.values(bookDB).find(b=>norm(b.title).includes(n)||n.includes(norm(b.title)))||null}
function responseText(resp){const c=resp?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>typeof x==='string'?x:(x?.text||'')).join('');if(typeof resp==='string')return resp;return ''}
function parseJSON(text){try{return JSON.parse(text)}catch(e){} const a=text.indexOf('{'),b=text.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(text.slice(a,b+1))}catch(e){}}return null}
function gradeLanguage(g){if(g<=2)return '句子短、非常具体、一次只推进一个思考；多用“谁/做了什么/为什么/如果”';if(g<=4)return '引导比较、因果、人物动机和转折；要求孩子说明理由';return '引导证据、反例、价值冲突、系统因素与评价，但仍使用小学生能懂的中文'}
async function aiChat(messages,extra={}){return await puter.ai.chat(messages,{model:MODEL,normalize:true,...extra})}